[tool.ruff]
line-length = 100 

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = ["ALL"]
ignore = [
  # Allow print statements
  "T201",
  # Allow "df" name in small script
  "PD901",
  # overlap with other rules
  "D212",
  # overlap with the ruff formatter
  "COM812",
  "COM819",
  "D206",
  "ISC001",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "W191",
]
fixable = ["ALL"]
unfixable = []

[tool.pyright]
typeCheckingMode = "standard"
